import Link from 'next/link';

const services = [
  { icon: 'fa-solid fa-rocket', name: 'Launch Website', text: 'A focused, polished website for a new business, service, or personal brand.', points: ['Up to 5 pages', 'Custom visual direction', 'Mobile-first build', 'Basic SEO and contact form'] },
  { icon: 'fa-solid fa-layer-group', name: 'Business Website', text: 'A complete digital home for businesses that need to look credible and convert.', points: ['Multi-page architecture', 'Content and conversion planning', 'CMS or easy-update setup', 'Analytics and launch support'], featured: true },
  { icon: 'fa-solid fa-cubes-stacked', name: 'Digital Product', text: 'A scalable React or Next.js experience for teams building something bigger.', points: ['Advanced interactions', 'Dashboards and integrations', 'Reusable component system', 'Performance-focused development'] },
];

export default function WebsiteDesigning() {
  return (
    <>
      <section className="page-hero detail-website-hero"><div className="hero-grid" /><div className="hero-mesh" /><div className="container detail-hero-content"><div className="section-label hero-animate"><i className="fa-solid fa-swatchbook" /> Website design</div><h1 className="hero-animate">Choose the right <span className="gradient-text">digital experience.</span></h1><p className="section-sub hero-animate">The homepage gives you the feeling. This page gives you the details: what we build, who it is for, and how we take it from idea to live website.</p><div className="flex gap-3 flex-wrap hero-animate"><Link href="/contact" className="btn btn-primary">Start a project <i className="fa-solid fa-arrow-right" /></Link><Link href="/#case-study" className="btn btn-outline">See our first project <i className="fa-solid fa-arrow-up-right-from-square" /></Link></div></div></section>

      <section className="section detail-service-section"><div className="container"><div className="section-header"><div className="section-label reveal">Find your fit</div><h2 className="section-title reveal">Not sure what you need? <span className="gradient-text">Start here.</span></h2><p className="section-sub mx-auto reveal">Every project is tailored. These three directions make it easier to understand where your website journey could begin.</p></div><div className="detail-service-grid">{services.map((service, index) => <article className={`glass-card detail-service-card reveal delay-${(index + 1) * 100} ${service.featured ? 'featured' : ''}`} key={service.name}>{service.featured && <span className="detail-service-badge">Most popular</span>}<div className="detail-service-icon"><i className={service.icon} /></div><h3>{service.name}</h3><p>{service.text}</p><ul>{service.points.map((point) => <li key={point}><i className="fa-solid fa-check" />{point}</li>)}</ul><Link href="/contact" className="btn btn-outline">Discuss this option <i className="fa-solid fa-arrow-right" /></Link></article>)}</div></div></section>

      <section className="section detail-stack-section"><div className="container"><div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"><div><div className="section-label reveal">What you get</div><h2 className="section-title reveal">The details behind the <span className="gradient-text">good feeling.</span></h2><p className="section-sub reveal">A good website is a system, not just a screen. We make sure the strategy, content, design, technology, and launch all work together.</p><Link href="/contact" className="btn btn-primary mt-8 reveal">Talk through your idea <i className="fa-solid fa-arrow-right" /></Link></div><div className="detail-stack-card glass-card reveal"><div className="detail-stack-row"><span>01</span><div><h3>Clear structure</h3><p>Visitors know where they are and what to do next.</p></div><i className="fa-solid fa-diagram-project" /></div><div className="detail-stack-row"><span>02</span><div><h3>Distinctive visuals</h3><p>Your website looks like your brand, not a template.</p></div><i className="fa-solid fa-wand-magic-sparkles" /></div><div className="detail-stack-row"><span>03</span><div><h3>Confident technology</h3><p>Fast, responsive, maintainable, and ready to grow.</p></div><i className="fa-solid fa-code" /></div></div></div></div></section>

      <section className="section detail-process-section"><div className="container"><div className="section-header"><div className="section-label reveal">Our process</div><h2 className="section-title reveal">From rough idea to <span className="gradient-text">real website.</span></h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-6"><div className="process-card reveal"><span className="process-card-number">01</span><h3>Discover</h3><p>We understand your audience, offer, and goals before touching the design.</p></div><div className="process-card reveal delay-100"><span className="process-card-number">02</span><h3>Design &amp; build</h3><p>We turn the strategy into a visual direction and a responsive experience.</p></div><div className="process-card reveal delay-200"><span className="process-card-number">03</span><h3>Refine &amp; launch</h3><p>We test, polish, launch, and support your next stage of growth.</p></div></div></div></section>

      <section className="cta-banner"><div className="container"><div className="section-label">Your next move</div><h2 className="section-title" style={{ color: '#fff' }}>Let&apos;s make your website <span className="gradient-text">the one they remember.</span></h2><p className="section-sub mx-auto" style={{ color: 'rgba(255,255,255,.78)' }}>Tell us what you are building and we&apos;ll help you choose the right starting point.</p><Link href="/contact" className="btn btn-accent mt-8">Start a conversation <i className="fa-solid fa-arrow-right" /></Link></div></section>
    </>
  );
}
