import Link from 'next/link';
import ClientEffects from '@/components/ClientEffects';

const services = [
  { number: '01', label: 'Web design', title: 'Make your first impression impossible to ignore.', text: 'Strategy-led websites, digital products, and landing pages that make your business easy to understand and hard to forget.', icon: 'fa-solid fa-wand-magic-sparkles', href: '/', tags: ['Brand websites', 'React / Next.js', 'Google Sites'], className: 'all-service-web' },
  { number: '02', label: 'Digital marketing', title: 'Turn attention into actual momentum.', text: 'Organic growth, paid campaigns, content, and conversion funnels built around the people you want to reach.', icon: 'fa-solid fa-chart-line', href: '/digital-marketing', tags: ['SEO', 'Paid ads', 'Growth funnels'], className: 'all-service-marketing' },
  { number: '03', label: 'Robotics & automation', title: 'Build what the future needs next.', text: 'From robotics education and R&D to smart factory systems and control software, we connect ideas to real-world action.', icon: 'fa-solid fa-robot', href: '/robotics-automation', tags: ['R&D', 'Industrial automation', 'Control software'], className: 'all-service-robotics' },
  { number: '04', label: 'Talent & growth services', title: 'Put the right people behind the work.', text: 'Flexible staffing, permanent hiring, and dedicated project teams for the next stage of your business.', icon: 'fa-solid fa-people-group', href: '/other-services', tags: ['Contract staffing', 'Permanent hiring', 'Project teams'], className: 'all-service-talent' },
];

const connections = [
  ['01', 'Clarify the opportunity', 'We start with the business problem, not a pre-selected service.'],
  ['02', 'Choose the right mix', 'Sometimes you need a website. Sometimes you need the team, growth, or system behind it.'],
  ['03', 'Make it move', 'We turn the plan into a useful, memorable, measurable next step.'],
];

export default function HomeOverview() {
  return (
    <div className="services-home">
      <ClientEffects />
      <section className="services-home-hero"><div className="services-home-orb services-home-orb-one" /><div className="services-home-orb services-home-orb-two" /><div className="services-home-grid" /><div className="container services-home-hero-inner"><div className="services-home-copy"><div className="glass-eyebrow hero-animate"><span className="glass-live-dot" /> Progic Technologies / the bigger picture</div><h1 className="hero-animate">Everything your next chapter needs to <span className="glass-gradient-text">move forward.</span></h1><p className="hero-animate">We design the digital presence, growth systems, intelligent technology, and teams that help ambitious businesses take their next step.</p><div className="flex gap-3 flex-wrap hero-animate"><Link href="/contact" className="glass-button glass-button-primary">Tell us what you&apos;re building <i className="fa-solid fa-arrow-right" /></Link><a href="#offerings" className="glass-button glass-button-ghost">Explore all services <i className="fa-solid fa-arrow-down" /></a></div></div><div className="services-home-stack hero-animate"><div className="services-stack-label">ONE PARTNER / FOUR DIRECTIONS</div><div className="services-stack-card stack-card-four"><i className="fa-solid fa-people-group" /><span>Talent &amp; growth</span></div><div className="services-stack-card stack-card-three"><i className="fa-solid fa-robot" /><span>Robotics &amp; automation</span></div><div className="services-stack-card stack-card-two"><i className="fa-solid fa-chart-line" /><span>Digital marketing</span></div><div className="services-stack-card stack-card-one"><i className="fa-solid fa-wand-magic-sparkles" /><span>Web design</span><b>↗</b></div></div></div></section>

      <div className="services-home-strip"><div className="container"><span>One team</span><i className="fa-solid fa-asterisk" /><span>Different disciplines</span><i className="fa-solid fa-asterisk" /><span>Shared ambition</span><i className="fa-solid fa-asterisk" /><span>Your next move</span></div></div>

      <section className="section all-services-section" id="offerings"><div className="container"><div className="section-header all-services-heading"><div className="glass-eyebrow reveal">What we offer</div><h2 className="reveal">Four ways to get <span className="glass-gradient-text">unstuck.</span></h2><p className="reveal">Start with the challenge. We&apos;ll help you find the right capability, not force you into a package.</p></div><div className="all-services-grid">{services.map((service, index) => <article className={`all-service-card ${service.className} reveal delay-${(index + 1) * 100}`} key={service.number}><div className="all-service-top"><span>{service.number}</span><i className={service.icon} /></div><small>{service.label}</small><h3>{service.title}</h3><p>{service.text}</p><div className="all-service-tags">{service.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><Link href={service.href} className="all-service-link">Explore service <i className="fa-solid fa-arrow-up-right-from-square" /></Link></article>)}</div></div></section>

      <section className="section services-connection-section"><div className="container"><div className="services-connection-heading"><div><div className="glass-eyebrow reveal">How we think</div><h2 className="reveal">The right answer is usually <span className="glass-gradient-text">connected.</span></h2></div><p className="reveal">A website can create the first impression. Marketing can bring the right people in. Technology and talent help you keep moving.</p></div><div className="services-connection-grid">{connections.map(([number, title, text], index) => <div className="services-connection-card reveal" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p>{index < 2 && <i className="fa-solid fa-arrow-right" />}</div>)}</div></div></section>

      <section className="section services-case-section"><div className="container services-case-grid"><div className="services-case-art reveal"><div className="services-case-window"><small>DEEPSEED TECHNOLOGIES</small><strong>One connected<br /><em>technology hub.</em></strong><div><span>Web</span><span>Growth</span><span>Robotics</span><span>Software</span></div></div><b>01 / LIVE CASE STUDY</b></div><div><div className="glass-eyebrow reveal">Our first website</div><h2 className="reveal">A complex business made <span className="glass-gradient-text">clear.</span></h2><p className="reveal">For Deepseed Technologies, we created a digital home that brings robotics, automation, software, digital marketing, and education into one confident story.</p><a href="https://www.deepseedtechnologies.com/" target="_blank" rel="noreferrer" className="glass-button glass-button-ghost reveal">Visit the live website <i className="fa-solid fa-arrow-up-right-from-square" /></a></div></div></section>

      <section className="services-home-cta"><div className="services-home-orb services-home-orb-cta" /><div className="container"><div className="glass-eyebrow">Start anywhere</div><h2>Have a problem,<br /><span className="glass-gradient-text">not a service name?</span></h2><p>That&apos;s exactly where we&apos;re useful. Tell us what you want to improve and we&apos;ll help you shape the next move.</p><Link href="/contact" className="glass-button glass-button-primary">Start a conversation <i className="fa-solid fa-arrow-right" /></Link></div></section>
    </div>
  );
}
